apiVersion: v1
kind: ServiceAccount
metadata:
  name: uac
  namespace: uac
  labels:
    app.kubernetes.io/name: universal-agent-connector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uac
  namespace: uac
  labels:
    app.kubernetes.io/name: universal-agent-connector
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uac
  namespace: uac
  labels:
    app.kubernetes.io/name: universal-agent-connector
subjects:
  - kind: ServiceAccount
    name: uac
    namespace: uac
roleRef:
  kind: Role
  name: uac
  apiGroup: rbac.authorization.k8s.io
